[tool.poetry]
name = "libsys-airflow"
version = "0.1.0"
description = "Airflow DAGS for migrating and managing ILS data into FOLIO along with other LibSys workflows"
authors = ["Jeremy Nelson <jpnelson@stanford.edu>", "Joshua Greben <jgreben@stanford.edu>", "Shelley Doljack", "Laura Wrubel", "Michael J. Giarlo <mjgiarlo@stanford.edu>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.10"
argparse-prompt = "^0.0.5"
jsonpath-ng = "^1.5.3"
numpy = "^1.22.3"
objectpath = "^0.6.1"
pandas = "^1.4.1"
pydantic = "^1.9.0"
pymarc = "^4.1.3"
folio-migration-tools = "1.7.8"
requests = "^2.28.2"
pyyaml = "^6.0"
python-dotenv = "^1.0.0"
alembic = "^1.10.4"
psycopg2-binary = "^2.9.6"
python-magic = "^0.4.27"

[tool.poetry.group.test.dependencies]
black = "~23.3.0"
coveralls = "~3.3.1"
coverage = "~6.5.0"
flake8 = "^6.0.0"
pytest = "^7.1.1"
pytest-cov = "^4.0.0"
pytest-mock = "^3.7.0"
# these are needed for running tests outside of the airflow docker container
# the airflow version here should be kept in sync with the docker image
apache-airflow = "2.6.0"
apache-airflow-providers-postgres = "5.4.0"
apache-airflow-providers-sftp = "^4.2.4"
requests-mock = "^1.10.0"
pytest-mock-resources = "^2.6.12"
beautifulsoup4 = "^4.12.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
exclude = 'vendor_loads_migration'
skip-string-normalization = true
color = true
