[tool.poetry]
name = "folio-airflow"
version = "0.1.0"
description = "Airflow DAGS for migrating ILS data into FOLIO"
authors = ["Jeremy Nelson <jpnelson@stanford.edu>", "Joshua Greben <jgreben@stanford.edu>", "Shelley Doljack <sdoljack@stanford.edu>"]
license = "Apache 2"

[tool.poetry.dependencies]
python = "^3.8"
pymarc = "^4.1.1"
apache-airflow = "^2.2.2"

[tool.poetry.dev-dependencies]
black = "^21.11b0"
pytest = "^6.2.5"
flake9 = "^3.8.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
