# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Folio Airflow CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install airflow dependencies
      run: |
        pip install -r requirements.txt
    - name: Install FOLIO-FSE tools
      run: |
        pip install folioclient folio-migration-tools folio-uuid
    - name: Lint with flake8
      run: |
        flake8 --ignore=E225,E501,F401,F811,W503
    - name: Test with pytest
      run: |
        coverage run -m pytest
        coverage lcov
        coveralls --service=github
