# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Folio Airflow CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Airflow + dependencies
        run: |
          pip install -r requirements.txt
          poetry install
      - name: Test with pytest
        run: |
          poetry run airflow db init
          poetry run pytest -rP
          poetry run coverage lcov
          poetry run coveralls --service=github
